// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mensagem_gerente_dados.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PacoteDados_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PacoteDados_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_mensagem_5fgerente_5fdados_2eproto() {
  protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "mensagem_gerente_dados.proto");
  GOOGLE_CHECK(file != NULL);
  PacoteDados_descriptor_ = file->message_type(0);
  static const int PacoteDados_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, dadosvisao_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, dadosestados_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, dadoscontrole_),
  };
  PacoteDados_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PacoteDados_descriptor_,
      PacoteDados::default_instance_,
      PacoteDados_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PacoteDados));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_mensagem_5fgerente_5fdados_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PacoteDados_descriptor_, &PacoteDados::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_mensagem_5fgerente_5fdados_2eproto() {
  delete PacoteDados::default_instance_;
  delete PacoteDados_reflection_;
}

void protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_messages_5frobocup_5fssl_5freferee_2eproto();
  ::protobuf_AddDesc_mensagem_5fgerente_5fvisao_2eproto();
  ::protobuf_AddDesc_mensagem_5fcontrole_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034mensagem_gerente_dados.proto\032\"messages"
    "_robocup_ssl_referee.proto\032\034mensagem_ger"
    "ente_visao.proto\032\027mensagem_controle.prot"
    "o\"{\n\013PacoteDados\022 \n\ndadosVisao\030\001 \001(\0132\014.P"
    "acoteVisao\022\"\n\014dadosEstados\030\002 \001(\0132\014.SSL_R"
    "eferee\022&\n\rdadosControle\030\003 \001(\0132\017.PacoteCo"
    "ntrole", 246);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mensagem_gerente_dados.proto", &protobuf_RegisterTypes);
  PacoteDados::default_instance_ = new PacoteDados();
  PacoteDados::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mensagem_5fgerente_5fdados_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mensagem_5fgerente_5fdados_2eproto {
  StaticDescriptorInitializer_mensagem_5fgerente_5fdados_2eproto() {
    protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();
  }
} static_descriptor_initializer_mensagem_5fgerente_5fdados_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int PacoteDados::kDadosVisaoFieldNumber;
const int PacoteDados::kDadosEstadosFieldNumber;
const int PacoteDados::kDadosControleFieldNumber;
#endif  // !_MSC_VER

PacoteDados::PacoteDados()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PacoteDados::InitAsDefaultInstance() {
  dadosvisao_ = const_cast< ::PacoteVisao*>(&::PacoteVisao::default_instance());
  dadosestados_ = const_cast< ::SSL_Referee*>(&::SSL_Referee::default_instance());
  dadoscontrole_ = const_cast< ::PacoteControle*>(&::PacoteControle::default_instance());
}

PacoteDados::PacoteDados(const PacoteDados& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PacoteDados::SharedCtor() {
  _cached_size_ = 0;
  dadosvisao_ = NULL;
  dadosestados_ = NULL;
  dadoscontrole_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PacoteDados::~PacoteDados() {
  SharedDtor();
}

void PacoteDados::SharedDtor() {
  if (this != default_instance_) {
    delete dadosvisao_;
    delete dadosestados_;
    delete dadoscontrole_;
  }
}

void PacoteDados::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PacoteDados::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PacoteDados_descriptor_;
}

const PacoteDados& PacoteDados::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();  return *default_instance_;
}

PacoteDados* PacoteDados::default_instance_ = NULL;

PacoteDados* PacoteDados::New() const {
  return new PacoteDados;
}

void PacoteDados::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_dadosvisao()) {
      if (dadosvisao_ != NULL) dadosvisao_->::PacoteVisao::Clear();
    }
    if (has_dadosestados()) {
      if (dadosestados_ != NULL) dadosestados_->::SSL_Referee::Clear();
    }
    if (has_dadoscontrole()) {
      if (dadoscontrole_ != NULL) dadoscontrole_->::PacoteControle::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PacoteDados::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .PacoteVisao dadosVisao = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dadosvisao()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dadosEstados;
        break;
      }
      
      // optional .SSL_Referee dadosEstados = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dadosEstados:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dadosestados()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_dadosControle;
        break;
      }
      
      // optional .PacoteControle dadosControle = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dadosControle:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dadoscontrole()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PacoteDados::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .PacoteVisao dadosVisao = 1;
  if (has_dadosvisao()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->dadosvisao(), output);
  }
  
  // optional .SSL_Referee dadosEstados = 2;
  if (has_dadosestados()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dadosestados(), output);
  }
  
  // optional .PacoteControle dadosControle = 3;
  if (has_dadoscontrole()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->dadoscontrole(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PacoteDados::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .PacoteVisao dadosVisao = 1;
  if (has_dadosvisao()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->dadosvisao(), target);
  }
  
  // optional .SSL_Referee dadosEstados = 2;
  if (has_dadosestados()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->dadosestados(), target);
  }
  
  // optional .PacoteControle dadosControle = 3;
  if (has_dadoscontrole()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->dadoscontrole(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PacoteDados::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .PacoteVisao dadosVisao = 1;
    if (has_dadosvisao()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dadosvisao());
    }
    
    // optional .SSL_Referee dadosEstados = 2;
    if (has_dadosestados()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dadosestados());
    }
    
    // optional .PacoteControle dadosControle = 3;
    if (has_dadoscontrole()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dadoscontrole());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PacoteDados::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PacoteDados* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PacoteDados*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PacoteDados::MergeFrom(const PacoteDados& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dadosvisao()) {
      mutable_dadosvisao()->::PacoteVisao::MergeFrom(from.dadosvisao());
    }
    if (from.has_dadosestados()) {
      mutable_dadosestados()->::SSL_Referee::MergeFrom(from.dadosestados());
    }
    if (from.has_dadoscontrole()) {
      mutable_dadoscontrole()->::PacoteControle::MergeFrom(from.dadoscontrole());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PacoteDados::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PacoteDados::CopyFrom(const PacoteDados& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PacoteDados::IsInitialized() const {
  
  if (has_dadosvisao()) {
    if (!this->dadosvisao().IsInitialized()) return false;
  }
  if (has_dadosestados()) {
    if (!this->dadosestados().IsInitialized()) return false;
  }
  if (has_dadoscontrole()) {
    if (!this->dadoscontrole().IsInitialized()) return false;
  }
  return true;
}

void PacoteDados::Swap(PacoteDados* other) {
  if (other != this) {
    std::swap(dadosvisao_, other->dadosvisao_);
    std::swap(dadosestados_, other->dadosestados_);
    std::swap(dadoscontrole_, other->dadoscontrole_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PacoteDados::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PacoteDados_descriptor_;
  metadata.reflection = PacoteDados_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
