// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem_gerente_dados.proto

#ifndef PROTOBUF_mensagem_5fgerente_5fdados_2eproto__INCLUDED
#define PROTOBUF_mensagem_5fgerente_5fdados_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "messages_robocup_ssl_referee.pb.h"
#include "mensagem_gerente_visao.pb.h"
#include "mensagem_controle.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();
void protobuf_AssignDesc_mensagem_5fgerente_5fdados_2eproto();
void protobuf_ShutdownFile_mensagem_5fgerente_5fdados_2eproto();

class PacoteDados;

// ===================================================================

class PacoteDados : public ::google::protobuf::Message {
 public:
  PacoteDados();
  virtual ~PacoteDados();
  
  PacoteDados(const PacoteDados& from);
  
  inline PacoteDados& operator=(const PacoteDados& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacoteDados& default_instance();
  
  void Swap(PacoteDados* other);
  
  // implements Message ----------------------------------------------
  
  PacoteDados* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PacoteDados& from);
  void MergeFrom(const PacoteDados& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .PacoteVisao dadosVisao = 1;
  inline bool has_dadosvisao() const;
  inline void clear_dadosvisao();
  static const int kDadosVisaoFieldNumber = 1;
  inline const ::PacoteVisao& dadosvisao() const;
  inline ::PacoteVisao* mutable_dadosvisao();
  inline ::PacoteVisao* release_dadosvisao();
  
  // optional .SSL_Referee dadosEstados = 2;
  inline bool has_dadosestados() const;
  inline void clear_dadosestados();
  static const int kDadosEstadosFieldNumber = 2;
  inline const ::SSL_Referee& dadosestados() const;
  inline ::SSL_Referee* mutable_dadosestados();
  inline ::SSL_Referee* release_dadosestados();
  
  // optional .PacoteControle dadosControle = 3;
  inline bool has_dadoscontrole() const;
  inline void clear_dadoscontrole();
  static const int kDadosControleFieldNumber = 3;
  inline const ::PacoteControle& dadoscontrole() const;
  inline ::PacoteControle* mutable_dadoscontrole();
  inline ::PacoteControle* release_dadoscontrole();
  
  // @@protoc_insertion_point(class_scope:PacoteDados)
 private:
  inline void set_has_dadosvisao();
  inline void clear_has_dadosvisao();
  inline void set_has_dadosestados();
  inline void clear_has_dadosestados();
  inline void set_has_dadoscontrole();
  inline void clear_has_dadoscontrole();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::PacoteVisao* dadosvisao_;
  ::SSL_Referee* dadosestados_;
  ::PacoteControle* dadoscontrole_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();
  friend void protobuf_AssignDesc_mensagem_5fgerente_5fdados_2eproto();
  friend void protobuf_ShutdownFile_mensagem_5fgerente_5fdados_2eproto();
  
  void InitAsDefaultInstance();
  static PacoteDados* default_instance_;
};
// ===================================================================


// ===================================================================

// PacoteDados

// optional .PacoteVisao dadosVisao = 1;
inline bool PacoteDados::has_dadosvisao() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PacoteDados::set_has_dadosvisao() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PacoteDados::clear_has_dadosvisao() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PacoteDados::clear_dadosvisao() {
  if (dadosvisao_ != NULL) dadosvisao_->::PacoteVisao::Clear();
  clear_has_dadosvisao();
}
inline const ::PacoteVisao& PacoteDados::dadosvisao() const {
  return dadosvisao_ != NULL ? *dadosvisao_ : *default_instance_->dadosvisao_;
}
inline ::PacoteVisao* PacoteDados::mutable_dadosvisao() {
  set_has_dadosvisao();
  if (dadosvisao_ == NULL) dadosvisao_ = new ::PacoteVisao;
  return dadosvisao_;
}
inline ::PacoteVisao* PacoteDados::release_dadosvisao() {
  clear_has_dadosvisao();
  ::PacoteVisao* temp = dadosvisao_;
  dadosvisao_ = NULL;
  return temp;
}

// optional .SSL_Referee dadosEstados = 2;
inline bool PacoteDados::has_dadosestados() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PacoteDados::set_has_dadosestados() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PacoteDados::clear_has_dadosestados() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PacoteDados::clear_dadosestados() {
  if (dadosestados_ != NULL) dadosestados_->::SSL_Referee::Clear();
  clear_has_dadosestados();
}
inline const ::SSL_Referee& PacoteDados::dadosestados() const {
  return dadosestados_ != NULL ? *dadosestados_ : *default_instance_->dadosestados_;
}
inline ::SSL_Referee* PacoteDados::mutable_dadosestados() {
  set_has_dadosestados();
  if (dadosestados_ == NULL) dadosestados_ = new ::SSL_Referee;
  return dadosestados_;
}
inline ::SSL_Referee* PacoteDados::release_dadosestados() {
  clear_has_dadosestados();
  ::SSL_Referee* temp = dadosestados_;
  dadosestados_ = NULL;
  return temp;
}

// optional .PacoteControle dadosControle = 3;
inline bool PacoteDados::has_dadoscontrole() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PacoteDados::set_has_dadoscontrole() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PacoteDados::clear_has_dadoscontrole() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PacoteDados::clear_dadoscontrole() {
  if (dadoscontrole_ != NULL) dadoscontrole_->::PacoteControle::Clear();
  clear_has_dadoscontrole();
}
inline const ::PacoteControle& PacoteDados::dadoscontrole() const {
  return dadoscontrole_ != NULL ? *dadoscontrole_ : *default_instance_->dadoscontrole_;
}
inline ::PacoteControle* PacoteDados::mutable_dadoscontrole() {
  set_has_dadoscontrole();
  if (dadoscontrole_ == NULL) dadoscontrole_ = new ::PacoteControle;
  return dadoscontrole_;
}
inline ::PacoteControle* PacoteDados::release_dadoscontrole() {
  clear_has_dadoscontrole();
  ::PacoteControle* temp = dadoscontrole_;
  dadoscontrole_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mensagem_5fgerente_5fdados_2eproto__INCLUDED
