// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variaveis_IA.proto

#ifndef PROTOBUF_variaveis_5fIA_2eproto__INCLUDED
#define PROTOBUF_variaveis_5fIA_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_variaveis_5fIA_2eproto();
void protobuf_AssignDesc_variaveis_5fIA_2eproto();
void protobuf_ShutdownFile_variaveis_5fIA_2eproto();

class pacote_variaveis_IA;

// ===================================================================

class pacote_variaveis_IA : public ::google::protobuf::Message {
 public:
  pacote_variaveis_IA();
  virtual ~pacote_variaveis_IA();
  
  pacote_variaveis_IA(const pacote_variaveis_IA& from);
  
  inline pacote_variaveis_IA& operator=(const pacote_variaveis_IA& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const pacote_variaveis_IA& default_instance();
  
  void Swap(pacote_variaveis_IA* other);
  
  // implements Message ----------------------------------------------
  
  pacote_variaveis_IA* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pacote_variaveis_IA& from);
  void MergeFrom(const pacote_variaveis_IA& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated string componente = 1;
  inline int componente_size() const;
  inline void clear_componente();
  static const int kComponenteFieldNumber = 1;
  inline const ::std::string& componente(int index) const;
  inline ::std::string* mutable_componente(int index);
  inline void set_componente(int index, const ::std::string& value);
  inline void set_componente(int index, const char* value);
  inline void set_componente(int index, const char* value, size_t size);
  inline ::std::string* add_componente();
  inline void add_componente(const ::std::string& value);
  inline void add_componente(const char* value);
  inline void add_componente(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& componente() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_componente();
  
  // repeated string nome_componente = 2;
  inline int nome_componente_size() const;
  inline void clear_nome_componente();
  static const int kNomeComponenteFieldNumber = 2;
  inline const ::std::string& nome_componente(int index) const;
  inline ::std::string* mutable_nome_componente(int index);
  inline void set_nome_componente(int index, const ::std::string& value);
  inline void set_nome_componente(int index, const char* value);
  inline void set_nome_componente(int index, const char* value, size_t size);
  inline ::std::string* add_nome_componente();
  inline void add_nome_componente(const ::std::string& value);
  inline void add_nome_componente(const char* value);
  inline void add_nome_componente(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& nome_componente() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_nome_componente();
  
  // repeated string valor_componente = 3;
  inline int valor_componente_size() const;
  inline void clear_valor_componente();
  static const int kValorComponenteFieldNumber = 3;
  inline const ::std::string& valor_componente(int index) const;
  inline ::std::string* mutable_valor_componente(int index);
  inline void set_valor_componente(int index, const ::std::string& value);
  inline void set_valor_componente(int index, const char* value);
  inline void set_valor_componente(int index, const char* value, size_t size);
  inline ::std::string* add_valor_componente();
  inline void add_valor_componente(const ::std::string& value);
  inline void add_valor_componente(const char* value);
  inline void add_valor_componente(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& valor_componente() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_valor_componente();
  
  // @@protoc_insertion_point(class_scope:pacote_variaveis_IA)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> componente_;
  ::google::protobuf::RepeatedPtrField< ::std::string> nome_componente_;
  ::google::protobuf::RepeatedPtrField< ::std::string> valor_componente_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_variaveis_5fIA_2eproto();
  friend void protobuf_AssignDesc_variaveis_5fIA_2eproto();
  friend void protobuf_ShutdownFile_variaveis_5fIA_2eproto();
  
  void InitAsDefaultInstance();
  static pacote_variaveis_IA* default_instance_;
};
// ===================================================================


// ===================================================================

// pacote_variaveis_IA

// repeated string componente = 1;
inline int pacote_variaveis_IA::componente_size() const {
  return componente_.size();
}
inline void pacote_variaveis_IA::clear_componente() {
  componente_.Clear();
}
inline const ::std::string& pacote_variaveis_IA::componente(int index) const {
  return componente_.Get(index);
}
inline ::std::string* pacote_variaveis_IA::mutable_componente(int index) {
  return componente_.Mutable(index);
}
inline void pacote_variaveis_IA::set_componente(int index, const ::std::string& value) {
  componente_.Mutable(index)->assign(value);
}
inline void pacote_variaveis_IA::set_componente(int index, const char* value) {
  componente_.Mutable(index)->assign(value);
}
inline void pacote_variaveis_IA::set_componente(int index, const char* value, size_t size) {
  componente_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* pacote_variaveis_IA::add_componente() {
  return componente_.Add();
}
inline void pacote_variaveis_IA::add_componente(const ::std::string& value) {
  componente_.Add()->assign(value);
}
inline void pacote_variaveis_IA::add_componente(const char* value) {
  componente_.Add()->assign(value);
}
inline void pacote_variaveis_IA::add_componente(const char* value, size_t size) {
  componente_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
pacote_variaveis_IA::componente() const {
  return componente_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
pacote_variaveis_IA::mutable_componente() {
  return &componente_;
}

// repeated string nome_componente = 2;
inline int pacote_variaveis_IA::nome_componente_size() const {
  return nome_componente_.size();
}
inline void pacote_variaveis_IA::clear_nome_componente() {
  nome_componente_.Clear();
}
inline const ::std::string& pacote_variaveis_IA::nome_componente(int index) const {
  return nome_componente_.Get(index);
}
inline ::std::string* pacote_variaveis_IA::mutable_nome_componente(int index) {
  return nome_componente_.Mutable(index);
}
inline void pacote_variaveis_IA::set_nome_componente(int index, const ::std::string& value) {
  nome_componente_.Mutable(index)->assign(value);
}
inline void pacote_variaveis_IA::set_nome_componente(int index, const char* value) {
  nome_componente_.Mutable(index)->assign(value);
}
inline void pacote_variaveis_IA::set_nome_componente(int index, const char* value, size_t size) {
  nome_componente_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* pacote_variaveis_IA::add_nome_componente() {
  return nome_componente_.Add();
}
inline void pacote_variaveis_IA::add_nome_componente(const ::std::string& value) {
  nome_componente_.Add()->assign(value);
}
inline void pacote_variaveis_IA::add_nome_componente(const char* value) {
  nome_componente_.Add()->assign(value);
}
inline void pacote_variaveis_IA::add_nome_componente(const char* value, size_t size) {
  nome_componente_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
pacote_variaveis_IA::nome_componente() const {
  return nome_componente_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
pacote_variaveis_IA::mutable_nome_componente() {
  return &nome_componente_;
}

// repeated string valor_componente = 3;
inline int pacote_variaveis_IA::valor_componente_size() const {
  return valor_componente_.size();
}
inline void pacote_variaveis_IA::clear_valor_componente() {
  valor_componente_.Clear();
}
inline const ::std::string& pacote_variaveis_IA::valor_componente(int index) const {
  return valor_componente_.Get(index);
}
inline ::std::string* pacote_variaveis_IA::mutable_valor_componente(int index) {
  return valor_componente_.Mutable(index);
}
inline void pacote_variaveis_IA::set_valor_componente(int index, const ::std::string& value) {
  valor_componente_.Mutable(index)->assign(value);
}
inline void pacote_variaveis_IA::set_valor_componente(int index, const char* value) {
  valor_componente_.Mutable(index)->assign(value);
}
inline void pacote_variaveis_IA::set_valor_componente(int index, const char* value, size_t size) {
  valor_componente_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* pacote_variaveis_IA::add_valor_componente() {
  return valor_componente_.Add();
}
inline void pacote_variaveis_IA::add_valor_componente(const ::std::string& value) {
  valor_componente_.Add()->assign(value);
}
inline void pacote_variaveis_IA::add_valor_componente(const char* value) {
  valor_componente_.Add()->assign(value);
}
inline void pacote_variaveis_IA::add_valor_componente(const char* value, size_t size) {
  valor_componente_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
pacote_variaveis_IA::valor_componente() const {
  return valor_componente_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
pacote_variaveis_IA::mutable_valor_componente() {
  return &valor_componente_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_variaveis_5fIA_2eproto__INCLUDED
