// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem_gerente_visao.proto

#ifndef PROTOBUF_mensagem_5fgerente_5fvisao_2eproto__INCLUDED
#define PROTOBUF_mensagem_5fgerente_5fvisao_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mensagem_5fgerente_5fvisao_2eproto();
void protobuf_AssignDesc_mensagem_5fgerente_5fvisao_2eproto();
void protobuf_ShutdownFile_mensagem_5fgerente_5fvisao_2eproto();

class PacoteBola;
class PacoteRobo;
class PacoteVisao;

// ===================================================================

class PacoteBola : public ::google::protobuf::Message {
 public:
  PacoteBola();
  virtual ~PacoteBola();
  
  PacoteBola(const PacoteBola& from);
  
  inline PacoteBola& operator=(const PacoteBola& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacoteBola& default_instance();
  
  void Swap(PacoteBola* other);
  
  // implements Message ----------------------------------------------
  
  PacoteBola* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PacoteBola& from);
  void MergeFrom(const PacoteBola& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // optional float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);
  
  // @@protoc_insertion_point(class_scope:PacoteBola)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_;
  float y_;
  float z_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_mensagem_5fgerente_5fvisao_2eproto();
  friend void protobuf_AssignDesc_mensagem_5fgerente_5fvisao_2eproto();
  friend void protobuf_ShutdownFile_mensagem_5fgerente_5fvisao_2eproto();
  
  void InitAsDefaultInstance();
  static PacoteBola* default_instance_;
};
// -------------------------------------------------------------------

class PacoteRobo : public ::google::protobuf::Message {
 public:
  PacoteRobo();
  virtual ~PacoteRobo();
  
  PacoteRobo(const PacoteRobo& from);
  
  inline PacoteRobo& operator=(const PacoteRobo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacoteRobo& default_instance();
  
  void Swap(PacoteRobo* other);
  
  // implements Message ----------------------------------------------
  
  PacoteRobo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PacoteRobo& from);
  void MergeFrom(const PacoteRobo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);
  
  // required float x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline float x() const;
  inline void set_x(float value);
  
  // required float y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline float y() const;
  inline void set_y(float value);
  
  // required float orientation = 4;
  inline bool has_orientation() const;
  inline void clear_orientation();
  static const int kOrientationFieldNumber = 4;
  inline float orientation() const;
  inline void set_orientation(float value);
  
  // @@protoc_insertion_point(class_scope:PacoteRobo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_orientation();
  inline void clear_has_orientation();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 id_;
  float x_;
  float y_;
  float orientation_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_mensagem_5fgerente_5fvisao_2eproto();
  friend void protobuf_AssignDesc_mensagem_5fgerente_5fvisao_2eproto();
  friend void protobuf_ShutdownFile_mensagem_5fgerente_5fvisao_2eproto();
  
  void InitAsDefaultInstance();
  static PacoteRobo* default_instance_;
};
// -------------------------------------------------------------------

class PacoteVisao : public ::google::protobuf::Message {
 public:
  PacoteVisao();
  virtual ~PacoteVisao();
  
  PacoteVisao(const PacoteVisao& from);
  
  inline PacoteVisao& operator=(const PacoteVisao& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacoteVisao& default_instance();
  
  void Swap(PacoteVisao* other);
  
  // implements Message ----------------------------------------------
  
  PacoteVisao* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PacoteVisao& from);
  void MergeFrom(const PacoteVisao& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 numeroFrame = 1;
  inline bool has_numeroframe() const;
  inline void clear_numeroframe();
  static const int kNumeroFrameFieldNumber = 1;
  inline ::google::protobuf::uint32 numeroframe() const;
  inline void set_numeroframe(::google::protobuf::uint32 value);
  
  // required double delay = 2;
  inline bool has_delay() const;
  inline void clear_delay();
  static const int kDelayFieldNumber = 2;
  inline double delay() const;
  inline void set_delay(double value);
  
  // required .PacoteBola bola = 3;
  inline bool has_bola() const;
  inline void clear_bola();
  static const int kBolaFieldNumber = 3;
  inline const ::PacoteBola& bola() const;
  inline ::PacoteBola* mutable_bola();
  inline ::PacoteBola* release_bola();
  
  // repeated .PacoteRobo robosEquipe = 4;
  inline int robosequipe_size() const;
  inline void clear_robosequipe();
  static const int kRobosEquipeFieldNumber = 4;
  inline const ::PacoteRobo& robosequipe(int index) const;
  inline ::PacoteRobo* mutable_robosequipe(int index);
  inline ::PacoteRobo* add_robosequipe();
  inline const ::google::protobuf::RepeatedPtrField< ::PacoteRobo >&
      robosequipe() const;
  inline ::google::protobuf::RepeatedPtrField< ::PacoteRobo >*
      mutable_robosequipe();
  
  // repeated .PacoteRobo robosAdversarios = 5;
  inline int robosadversarios_size() const;
  inline void clear_robosadversarios();
  static const int kRobosAdversariosFieldNumber = 5;
  inline const ::PacoteRobo& robosadversarios(int index) const;
  inline ::PacoteRobo* mutable_robosadversarios(int index);
  inline ::PacoteRobo* add_robosadversarios();
  inline const ::google::protobuf::RepeatedPtrField< ::PacoteRobo >&
      robosadversarios() const;
  inline ::google::protobuf::RepeatedPtrField< ::PacoteRobo >*
      mutable_robosadversarios();
  
  // @@protoc_insertion_point(class_scope:PacoteVisao)
 private:
  inline void set_has_numeroframe();
  inline void clear_has_numeroframe();
  inline void set_has_delay();
  inline void clear_has_delay();
  inline void set_has_bola();
  inline void clear_has_bola();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  double delay_;
  ::PacoteBola* bola_;
  ::google::protobuf::RepeatedPtrField< ::PacoteRobo > robosequipe_;
  ::google::protobuf::RepeatedPtrField< ::PacoteRobo > robosadversarios_;
  ::google::protobuf::uint32 numeroframe_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_mensagem_5fgerente_5fvisao_2eproto();
  friend void protobuf_AssignDesc_mensagem_5fgerente_5fvisao_2eproto();
  friend void protobuf_ShutdownFile_mensagem_5fgerente_5fvisao_2eproto();
  
  void InitAsDefaultInstance();
  static PacoteVisao* default_instance_;
};
// ===================================================================


// ===================================================================

// PacoteBola

// required float x = 1;
inline bool PacoteBola::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PacoteBola::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PacoteBola::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PacoteBola::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float PacoteBola::x() const {
  return x_;
}
inline void PacoteBola::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 2;
inline bool PacoteBola::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PacoteBola::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PacoteBola::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PacoteBola::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float PacoteBola::y() const {
  return y_;
}
inline void PacoteBola::set_y(float value) {
  set_has_y();
  y_ = value;
}

// optional float z = 3;
inline bool PacoteBola::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PacoteBola::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PacoteBola::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PacoteBola::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float PacoteBola::z() const {
  return z_;
}
inline void PacoteBola::set_z(float value) {
  set_has_z();
  z_ = value;
}

// -------------------------------------------------------------------

// PacoteRobo

// required uint32 id = 1;
inline bool PacoteRobo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PacoteRobo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PacoteRobo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PacoteRobo::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 PacoteRobo::id() const {
  return id_;
}
inline void PacoteRobo::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required float x = 2;
inline bool PacoteRobo::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PacoteRobo::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PacoteRobo::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PacoteRobo::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float PacoteRobo::x() const {
  return x_;
}
inline void PacoteRobo::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 3;
inline bool PacoteRobo::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PacoteRobo::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PacoteRobo::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PacoteRobo::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float PacoteRobo::y() const {
  return y_;
}
inline void PacoteRobo::set_y(float value) {
  set_has_y();
  y_ = value;
}

// required float orientation = 4;
inline bool PacoteRobo::has_orientation() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PacoteRobo::set_has_orientation() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PacoteRobo::clear_has_orientation() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PacoteRobo::clear_orientation() {
  orientation_ = 0;
  clear_has_orientation();
}
inline float PacoteRobo::orientation() const {
  return orientation_;
}
inline void PacoteRobo::set_orientation(float value) {
  set_has_orientation();
  orientation_ = value;
}

// -------------------------------------------------------------------

// PacoteVisao

// required uint32 numeroFrame = 1;
inline bool PacoteVisao::has_numeroframe() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PacoteVisao::set_has_numeroframe() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PacoteVisao::clear_has_numeroframe() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PacoteVisao::clear_numeroframe() {
  numeroframe_ = 0u;
  clear_has_numeroframe();
}
inline ::google::protobuf::uint32 PacoteVisao::numeroframe() const {
  return numeroframe_;
}
inline void PacoteVisao::set_numeroframe(::google::protobuf::uint32 value) {
  set_has_numeroframe();
  numeroframe_ = value;
}

// required double delay = 2;
inline bool PacoteVisao::has_delay() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PacoteVisao::set_has_delay() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PacoteVisao::clear_has_delay() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PacoteVisao::clear_delay() {
  delay_ = 0;
  clear_has_delay();
}
inline double PacoteVisao::delay() const {
  return delay_;
}
inline void PacoteVisao::set_delay(double value) {
  set_has_delay();
  delay_ = value;
}

// required .PacoteBola bola = 3;
inline bool PacoteVisao::has_bola() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PacoteVisao::set_has_bola() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PacoteVisao::clear_has_bola() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PacoteVisao::clear_bola() {
  if (bola_ != NULL) bola_->::PacoteBola::Clear();
  clear_has_bola();
}
inline const ::PacoteBola& PacoteVisao::bola() const {
  return bola_ != NULL ? *bola_ : *default_instance_->bola_;
}
inline ::PacoteBola* PacoteVisao::mutable_bola() {
  set_has_bola();
  if (bola_ == NULL) bola_ = new ::PacoteBola;
  return bola_;
}
inline ::PacoteBola* PacoteVisao::release_bola() {
  clear_has_bola();
  ::PacoteBola* temp = bola_;
  bola_ = NULL;
  return temp;
}

// repeated .PacoteRobo robosEquipe = 4;
inline int PacoteVisao::robosequipe_size() const {
  return robosequipe_.size();
}
inline void PacoteVisao::clear_robosequipe() {
  robosequipe_.Clear();
}
inline const ::PacoteRobo& PacoteVisao::robosequipe(int index) const {
  return robosequipe_.Get(index);
}
inline ::PacoteRobo* PacoteVisao::mutable_robosequipe(int index) {
  return robosequipe_.Mutable(index);
}
inline ::PacoteRobo* PacoteVisao::add_robosequipe() {
  return robosequipe_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PacoteRobo >&
PacoteVisao::robosequipe() const {
  return robosequipe_;
}
inline ::google::protobuf::RepeatedPtrField< ::PacoteRobo >*
PacoteVisao::mutable_robosequipe() {
  return &robosequipe_;
}

// repeated .PacoteRobo robosAdversarios = 5;
inline int PacoteVisao::robosadversarios_size() const {
  return robosadversarios_.size();
}
inline void PacoteVisao::clear_robosadversarios() {
  robosadversarios_.Clear();
}
inline const ::PacoteRobo& PacoteVisao::robosadversarios(int index) const {
  return robosadversarios_.Get(index);
}
inline ::PacoteRobo* PacoteVisao::mutable_robosadversarios(int index) {
  return robosadversarios_.Mutable(index);
}
inline ::PacoteRobo* PacoteVisao::add_robosadversarios() {
  return robosadversarios_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PacoteRobo >&
PacoteVisao::robosadversarios() const {
  return robosadversarios_;
}
inline ::google::protobuf::RepeatedPtrField< ::PacoteRobo >*
PacoteVisao::mutable_robosadversarios() {
  return &robosadversarios_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mensagem_5fgerente_5fvisao_2eproto__INCLUDED
