// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mensagem_ia_gerente_dados.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PacoteVelocidades_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PacoteVelocidades_reflection_ = NULL;
const ::google::protobuf::Descriptor* PacoteIAGerenteDados_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PacoteIAGerenteDados_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_mensagem_5fia_5fgerente_5fdados_2eproto() {
  protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "mensagem_ia_gerente_dados.proto");
  GOOGLE_CHECK(file != NULL);
  PacoteVelocidades_descriptor_ = file->message_type(0);
  static const int PacoteVelocidades_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, vx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, vy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, vtheta_),
  };
  PacoteVelocidades_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PacoteVelocidades_descriptor_,
      PacoteVelocidades::default_instance_,
      PacoteVelocidades_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PacoteVelocidades));
  PacoteIAGerenteDados_descriptor_ = file->message_type(1);
  static const int PacoteIAGerenteDados_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, numframe_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, velocidades_),
  };
  PacoteIAGerenteDados_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PacoteIAGerenteDados_descriptor_,
      PacoteIAGerenteDados::default_instance_,
      PacoteIAGerenteDados_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PacoteIAGerenteDados));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_mensagem_5fia_5fgerente_5fdados_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PacoteVelocidades_descriptor_, &PacoteVelocidades::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PacoteIAGerenteDados_descriptor_, &PacoteIAGerenteDados::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_mensagem_5fia_5fgerente_5fdados_2eproto() {
  delete PacoteVelocidades::default_instance_;
  delete PacoteVelocidades_reflection_;
  delete PacoteIAGerenteDados::default_instance_;
  delete PacoteIAGerenteDados_reflection_;
}

void protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\037mensagem_ia_gerente_dados.proto\"G\n\021Pac"
    "oteVelocidades\022\n\n\002id\030\001 \002(\r\022\n\n\002vx\030\002 \002(\002\022\n"
    "\n\002vy\030\003 \002(\002\022\016\n\006vtheta\030\004 \002(\002\"Q\n\024PacoteIAGe"
    "renteDados\022\020\n\010numFrame\030\001 \002(\r\022\'\n\013velocida"
    "des\030\002 \003(\0132\022.PacoteVelocidades", 189);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mensagem_ia_gerente_dados.proto", &protobuf_RegisterTypes);
  PacoteVelocidades::default_instance_ = new PacoteVelocidades();
  PacoteIAGerenteDados::default_instance_ = new PacoteIAGerenteDados();
  PacoteVelocidades::default_instance_->InitAsDefaultInstance();
  PacoteIAGerenteDados::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mensagem_5fia_5fgerente_5fdados_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mensagem_5fia_5fgerente_5fdados_2eproto {
  StaticDescriptorInitializer_mensagem_5fia_5fgerente_5fdados_2eproto() {
    protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();
  }
} static_descriptor_initializer_mensagem_5fia_5fgerente_5fdados_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int PacoteVelocidades::kIdFieldNumber;
const int PacoteVelocidades::kVxFieldNumber;
const int PacoteVelocidades::kVyFieldNumber;
const int PacoteVelocidades::kVthetaFieldNumber;
#endif  // !_MSC_VER

PacoteVelocidades::PacoteVelocidades()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PacoteVelocidades::InitAsDefaultInstance() {
}

PacoteVelocidades::PacoteVelocidades(const PacoteVelocidades& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PacoteVelocidades::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  vx_ = 0;
  vy_ = 0;
  vtheta_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PacoteVelocidades::~PacoteVelocidades() {
  SharedDtor();
}

void PacoteVelocidades::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PacoteVelocidades::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PacoteVelocidades::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PacoteVelocidades_descriptor_;
}

const PacoteVelocidades& PacoteVelocidades::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();  return *default_instance_;
}

PacoteVelocidades* PacoteVelocidades::default_instance_ = NULL;

PacoteVelocidades* PacoteVelocidades::New() const {
  return new PacoteVelocidades;
}

void PacoteVelocidades::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0u;
    vx_ = 0;
    vy_ = 0;
    vtheta_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PacoteVelocidades::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_vx;
        break;
      }
      
      // required float vx = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_vx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vx_)));
          set_has_vx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_vy;
        break;
      }
      
      // required float vy = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_vy:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vy_)));
          set_has_vy();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_vtheta;
        break;
      }
      
      // required float vtheta = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_vtheta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vtheta_)));
          set_has_vtheta();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PacoteVelocidades::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }
  
  // required float vx = 2;
  if (has_vx()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->vx(), output);
  }
  
  // required float vy = 3;
  if (has_vy()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->vy(), output);
  }
  
  // required float vtheta = 4;
  if (has_vtheta()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->vtheta(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PacoteVelocidades::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }
  
  // required float vx = 2;
  if (has_vx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->vx(), target);
  }
  
  // required float vy = 3;
  if (has_vy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->vy(), target);
  }
  
  // required float vtheta = 4;
  if (has_vtheta()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->vtheta(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PacoteVelocidades::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }
    
    // required float vx = 2;
    if (has_vx()) {
      total_size += 1 + 4;
    }
    
    // required float vy = 3;
    if (has_vy()) {
      total_size += 1 + 4;
    }
    
    // required float vtheta = 4;
    if (has_vtheta()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PacoteVelocidades::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PacoteVelocidades* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PacoteVelocidades*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PacoteVelocidades::MergeFrom(const PacoteVelocidades& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_vx()) {
      set_vx(from.vx());
    }
    if (from.has_vy()) {
      set_vy(from.vy());
    }
    if (from.has_vtheta()) {
      set_vtheta(from.vtheta());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PacoteVelocidades::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PacoteVelocidades::CopyFrom(const PacoteVelocidades& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PacoteVelocidades::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  
  return true;
}

void PacoteVelocidades::Swap(PacoteVelocidades* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(vx_, other->vx_);
    std::swap(vy_, other->vy_);
    std::swap(vtheta_, other->vtheta_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PacoteVelocidades::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PacoteVelocidades_descriptor_;
  metadata.reflection = PacoteVelocidades_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PacoteIAGerenteDados::kNumFrameFieldNumber;
const int PacoteIAGerenteDados::kVelocidadesFieldNumber;
#endif  // !_MSC_VER

PacoteIAGerenteDados::PacoteIAGerenteDados()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PacoteIAGerenteDados::InitAsDefaultInstance() {
}

PacoteIAGerenteDados::PacoteIAGerenteDados(const PacoteIAGerenteDados& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PacoteIAGerenteDados::SharedCtor() {
  _cached_size_ = 0;
  numframe_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PacoteIAGerenteDados::~PacoteIAGerenteDados() {
  SharedDtor();
}

void PacoteIAGerenteDados::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PacoteIAGerenteDados::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PacoteIAGerenteDados::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PacoteIAGerenteDados_descriptor_;
}

const PacoteIAGerenteDados& PacoteIAGerenteDados::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();  return *default_instance_;
}

PacoteIAGerenteDados* PacoteIAGerenteDados::default_instance_ = NULL;

PacoteIAGerenteDados* PacoteIAGerenteDados::New() const {
  return new PacoteIAGerenteDados;
}

void PacoteIAGerenteDados::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    numframe_ = 0u;
  }
  velocidades_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PacoteIAGerenteDados::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 numFrame = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &numframe_)));
          set_has_numframe();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_velocidades;
        break;
      }
      
      // repeated .PacoteVelocidades velocidades = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_velocidades:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_velocidades()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_velocidades;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PacoteIAGerenteDados::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 numFrame = 1;
  if (has_numframe()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->numframe(), output);
  }
  
  // repeated .PacoteVelocidades velocidades = 2;
  for (int i = 0; i < this->velocidades_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->velocidades(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PacoteIAGerenteDados::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 numFrame = 1;
  if (has_numframe()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->numframe(), target);
  }
  
  // repeated .PacoteVelocidades velocidades = 2;
  for (int i = 0; i < this->velocidades_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->velocidades(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PacoteIAGerenteDados::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 numFrame = 1;
    if (has_numframe()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->numframe());
    }
    
  }
  // repeated .PacoteVelocidades velocidades = 2;
  total_size += 1 * this->velocidades_size();
  for (int i = 0; i < this->velocidades_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->velocidades(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PacoteIAGerenteDados::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PacoteIAGerenteDados* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PacoteIAGerenteDados*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PacoteIAGerenteDados::MergeFrom(const PacoteIAGerenteDados& from) {
  GOOGLE_CHECK_NE(&from, this);
  velocidades_.MergeFrom(from.velocidades_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_numframe()) {
      set_numframe(from.numframe());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PacoteIAGerenteDados::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PacoteIAGerenteDados::CopyFrom(const PacoteIAGerenteDados& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PacoteIAGerenteDados::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  for (int i = 0; i < velocidades_size(); i++) {
    if (!this->velocidades(i).IsInitialized()) return false;
  }
  return true;
}

void PacoteIAGerenteDados::Swap(PacoteIAGerenteDados* other) {
  if (other != this) {
    std::swap(numframe_, other->numframe_);
    velocidades_.Swap(&other->velocidades_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PacoteIAGerenteDados::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PacoteIAGerenteDados_descriptor_;
  metadata.reflection = PacoteIAGerenteDados_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
