// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "variaveis_IA.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* pacote_variaveis_IA_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pacote_variaveis_IA_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_variaveis_5fIA_2eproto() {
  protobuf_AddDesc_variaveis_5fIA_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "variaveis_IA.proto");
  GOOGLE_CHECK(file != NULL);
  pacote_variaveis_IA_descriptor_ = file->message_type(0);
  static const int pacote_variaveis_IA_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pacote_variaveis_IA, componente_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pacote_variaveis_IA, nome_componente_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pacote_variaveis_IA, valor_componente_),
  };
  pacote_variaveis_IA_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      pacote_variaveis_IA_descriptor_,
      pacote_variaveis_IA::default_instance_,
      pacote_variaveis_IA_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pacote_variaveis_IA, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pacote_variaveis_IA, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(pacote_variaveis_IA));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_variaveis_5fIA_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    pacote_variaveis_IA_descriptor_, &pacote_variaveis_IA::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_variaveis_5fIA_2eproto() {
  delete pacote_variaveis_IA::default_instance_;
  delete pacote_variaveis_IA_reflection_;
}

void protobuf_AddDesc_variaveis_5fIA_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022variaveis_IA.proto\"\\\n\023pacote_variaveis"
    "_IA\022\022\n\ncomponente\030\001 \003(\t\022\027\n\017nome_componen"
    "te\030\002 \003(\t\022\030\n\020valor_componente\030\003 \003(\t", 114);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "variaveis_IA.proto", &protobuf_RegisterTypes);
  pacote_variaveis_IA::default_instance_ = new pacote_variaveis_IA();
  pacote_variaveis_IA::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_variaveis_5fIA_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_variaveis_5fIA_2eproto {
  StaticDescriptorInitializer_variaveis_5fIA_2eproto() {
    protobuf_AddDesc_variaveis_5fIA_2eproto();
  }
} static_descriptor_initializer_variaveis_5fIA_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int pacote_variaveis_IA::kComponenteFieldNumber;
const int pacote_variaveis_IA::kNomeComponenteFieldNumber;
const int pacote_variaveis_IA::kValorComponenteFieldNumber;
#endif  // !_MSC_VER

pacote_variaveis_IA::pacote_variaveis_IA()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void pacote_variaveis_IA::InitAsDefaultInstance() {
}

pacote_variaveis_IA::pacote_variaveis_IA(const pacote_variaveis_IA& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void pacote_variaveis_IA::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

pacote_variaveis_IA::~pacote_variaveis_IA() {
  SharedDtor();
}

void pacote_variaveis_IA::SharedDtor() {
  if (this != default_instance_) {
  }
}

void pacote_variaveis_IA::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pacote_variaveis_IA::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pacote_variaveis_IA_descriptor_;
}

const pacote_variaveis_IA& pacote_variaveis_IA::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_variaveis_5fIA_2eproto();  return *default_instance_;
}

pacote_variaveis_IA* pacote_variaveis_IA::default_instance_ = NULL;

pacote_variaveis_IA* pacote_variaveis_IA::New() const {
  return new pacote_variaveis_IA;
}

void pacote_variaveis_IA::Clear() {
  componente_.Clear();
  nome_componente_.Clear();
  valor_componente_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool pacote_variaveis_IA::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string componente = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_componente:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_componente()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->componente(0).data(), this->componente(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_componente;
        if (input->ExpectTag(18)) goto parse_nome_componente;
        break;
      }
      
      // repeated string nome_componente = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_nome_componente:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_nome_componente()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->nome_componente(0).data(), this->nome_componente(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_nome_componente;
        if (input->ExpectTag(26)) goto parse_valor_componente;
        break;
      }
      
      // repeated string valor_componente = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_valor_componente:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_valor_componente()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->valor_componente(0).data(), this->valor_componente(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_valor_componente;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void pacote_variaveis_IA::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string componente = 1;
  for (int i = 0; i < this->componente_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->componente(i).data(), this->componente(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->componente(i), output);
  }
  
  // repeated string nome_componente = 2;
  for (int i = 0; i < this->nome_componente_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->nome_componente(i).data(), this->nome_componente(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->nome_componente(i), output);
  }
  
  // repeated string valor_componente = 3;
  for (int i = 0; i < this->valor_componente_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->valor_componente(i).data(), this->valor_componente(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->valor_componente(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* pacote_variaveis_IA::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string componente = 1;
  for (int i = 0; i < this->componente_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->componente(i).data(), this->componente(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->componente(i), target);
  }
  
  // repeated string nome_componente = 2;
  for (int i = 0; i < this->nome_componente_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->nome_componente(i).data(), this->nome_componente(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->nome_componente(i), target);
  }
  
  // repeated string valor_componente = 3;
  for (int i = 0; i < this->valor_componente_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->valor_componente(i).data(), this->valor_componente(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->valor_componente(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int pacote_variaveis_IA::ByteSize() const {
  int total_size = 0;
  
  // repeated string componente = 1;
  total_size += 1 * this->componente_size();
  for (int i = 0; i < this->componente_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->componente(i));
  }
  
  // repeated string nome_componente = 2;
  total_size += 1 * this->nome_componente_size();
  for (int i = 0; i < this->nome_componente_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->nome_componente(i));
  }
  
  // repeated string valor_componente = 3;
  total_size += 1 * this->valor_componente_size();
  for (int i = 0; i < this->valor_componente_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->valor_componente(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pacote_variaveis_IA::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const pacote_variaveis_IA* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const pacote_variaveis_IA*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void pacote_variaveis_IA::MergeFrom(const pacote_variaveis_IA& from) {
  GOOGLE_CHECK_NE(&from, this);
  componente_.MergeFrom(from.componente_);
  nome_componente_.MergeFrom(from.nome_componente_);
  valor_componente_.MergeFrom(from.valor_componente_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void pacote_variaveis_IA::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pacote_variaveis_IA::CopyFrom(const pacote_variaveis_IA& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pacote_variaveis_IA::IsInitialized() const {
  
  return true;
}

void pacote_variaveis_IA::Swap(pacote_variaveis_IA* other) {
  if (other != this) {
    componente_.Swap(&other->componente_);
    nome_componente_.Swap(&other->nome_componente_);
    valor_componente_.Swap(&other->valor_componente_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata pacote_variaveis_IA::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pacote_variaveis_IA_descriptor_;
  metadata.reflection = pacote_variaveis_IA_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
